### PR TITLE
test: add workflows

### LINKED ISSUE #32: Review Act tests in CI
Act currently produces Docker container errors when running tests in CI:

> ErrorsError: failed to create container: 'Error response from daemon: Conflict. The container name "/act-Test-compare-run-46e0747fd6c3bc782d74da83bbf464f9a6d9ce2063e24fa643739af7fde6acfa" is already in use by container "038de15db37ae72e6391140357bedd7759914f7dd4e6027ab4728cbd8d30c426". You have to remove (or rename) that container to be able to reuse that name.'

> ErrorsError: Error response from daemon: remove act-Test-compare-run-46e0747fd6c3bc782d74da83bbf464f9a6d9ce2063e24fa643739af7fde6acfa: volume is in use - [038de15db37ae72e6391140357bedd7759914f7dd4e6027ab4728cbd8d30c426]

> ErrorsError: failed to start container: Error response from daemon: container is marked for removal and cannot be started

Despite these errors, the enabled tests still have an Act result, and still pass. Enabling the `label` tests produces the following error in CI and the remaining tests do not complete:

> Errorspanic: runtime error: slice bounds out of range [:-1]

### PR DESCRIPTION
**Pull request by ianlnf**
- Adds a separate workflow file for each test
- Improves test folder structure
- Reinstates label tests

Resolves #32 

> Note that the tests occasionally fail in CI, so the tests have been temporarily disabled in the CI workflow. Issue #34 has been raised to review the Docker container error. The tests do run locally.

### CODE REVIEW

**Comment by simoneb** [comment]
@ianlnf are you looking for a review on this? if so, fix CI first please

**Comment by ianlnf** [comment]
> @ianlnf are you looking for a review on this? if so, fix CI first please

Updated now, ready for review. The logging added shows that Act tests do fail occasionally in CI with a Docker container error, but run locally. I've disabled the tests in CI and added issue #34. Options are removing the tests (no automated testing) or resolving the issue. But I think either option should be done after this PR is merged, as it has improved test structure anyway. The local tests may be of some value.

**Comment by simoneb** [comment]
My recommendation is to ditch act altogether and write unit test as we did in all out other actions. Are you up for picking this up?

**Comment by simoneb** [comment]
> > My recommendation is to ditch act altogether and write unit test as we did in all out other actions. Are you up for picking this up?
> 
> This is a purely composite action, there is no custom code to unit test

That's exactly the idea. Logic should live in code, not in yaml. I'd turn this into a JS action, ditch act and write pure unit tests for the logic.

**Comment by ianlnf** [comment]
> > > My recommendation is to ditch act altogether and write unit test as we did in all out other actions. Are you up for picking this up?
> > 
> > 
> > This is a purely composite action, there is no custom code to unit test
> 
> That's exactly the idea. Logic should live in code, not in yaml. I'd turn this into a JS action, ditch act and write pure unit tests for the logic.

I still think there is value in pursuing an effective mechanism for developing integration tests with composite actions longer term. Their raison d'etre is the reuse of logic within YAML, allowing existing actions to be repurposed to produce custom behaviour efficiently. Even if this action were to be refactored to JS/TS, which arguably is unnecessary here, it may still remain a composite action with custom code via github-script, e.g. if it wished to reuse actions such as input validation, copying of files, checkout etc. Testing only custom code in this case with unit tests may be sufficient, but may not be ideal. Integration tests could offer broader validation and less coupling to the production code.

I think either way though, this PR could be merged and issue #34 assessed for effort vs a refactor. It may be a configuration error or an issue that may be resolved in future Act versions. There is an issue with duplicate Act job names that can be reviewed. I do think the act-js API can be improved and offer additional features such as mocking of composite action steps and inputs. This would reduce the boilerplate and remove the need to check for `env.ACT` within the action metadata.

**Comment by simoneb** [comment]
I'm going to close this PR as it will be difficult to hand over to somebody else.

**Pull request closed without merging**
