### PR TITLE
Delete check-linked-issues.yml

### PR DESCRIPTION
**Pull request by RafaelGSS**
I don't think we should have this action in this project.

### CODE REVIEW

**Comment by simoneb** [comment]
We should always have issues linked to pull requests, so yes we should have this action

**Comment by RafaelGSS** [comment]
> We should always have issues linked to pull requests, so yes we should have this action

As an organizational project, yes. But, this is an open-source project. Why should we care about creating an issue of something that doesn't need an issue? It's not just a waste of time?

**Comment by simoneb** [comment]
Because there's no point in creating a pull request that doesn't solve an issue or implements a feature.

**Comment by ShogunPanda** [comment]
I agree with Rafael, sometimes is just unneeded noise.
I haven't checked the deep behavior so it might already be the case, but at least I would downgrade this check to be a warning only.

**Comment by simoneb** [comment]
Folks please first make sure you understand how all of our repos are configured and why for the sake of consistency introducing this exception doesn't make sense, in addition to this never having been a required check. Because it is my team that maintains this repo, in addition to dozens or even hundreds others, consistency is a necessary quality we need to keep.

**Comment by ShogunPanda** [comment]
Which makes absolutely sense.
My suggestion (and only a suggestion since you have a broader vision of the repos) was just to make sure that this is just a warning and not a blocker (since sometimes creating an issue would be too much consuming compared to just sending a quick PR).

And, to clarify, I never meant this suggestion to be an exception: if applied, it should be extended everywhere.

**Comment by simoneb** [comment]
I believe there are more important things that we can focus on than an action being used here, primarily because it's used literally in all of our repositories created in the last few years, and that is not blocking PRs from being merged anyway. The reason why we have this action is that we want to keep track of the issues we work on, be them bugs or features, so this action is to encourage linking PRs to issues.

**Pull request closed without merging**
